### ISSUE TITLE
O scroll não vai para o topo após trocar de pagina

### ISSUE THREAD

**Issue by joaopedrosgs** [petbccufscar/sitedodc-frontend#16]
creio que isso possa ajudar: https://stackoverflow.com/questions/36904185/react-router-scroll-to-top-on-every-transition

**Comment by DaanMoura** [comment]
Problema corrigido por #36

**Comment by DaanMoura** [comment]
Não funcionou no heroku. (porque?)

**Comment by DaanMoura** [comment]
Corrigido por #37
